# Kick message.
# Supported placeholders: %name% (player name)
kick.message: "Authorization error: ensure either you installed correctly the MOD and you have entered a token at the server config page or contact the server's admin"

# The time for which the player must send the correct token.
# Supported placeholders: %ping% (player ping)
# Supported math operators: +, -, *, /, (, ), ^, sqrt, sin, cos, tan.
kick.delay: "%ping% + 150"

# Tokens. example:
# MCNAME: "TOKEN"
# NikSne: "Ai"
# WolfCamera: "Auf"
# MoonyOwlet: "Hogwarts"
